### ISSUE TITLE
Can't install/build

### ISSUE THREAD

**Issue by cidrblock** [TykTechnologies/tyk-sync#1]
Ubuntu 16.04

```
deployment@ubuntu:~/tyk-git$ go install github.com/TykTechnologies/tyk-git
src/github.com/TykTechnologies/tyk-git/vendor/github.com/levigross/grequests/request.go:22:2: cannot find package "context" in any of:
	/home/deployment/tyk-git/src/github.com/TykTechnologies/tyk-git/vendor/context (vendor tree)
	/usr/lib/go-1.6/src/context (from $GOROOT)
	/home/deployment/tyk-git/src/context (from $GOPATH)
deployment@ubuntu:~/tyk-git$ go get github.com/TykTechnologies/tyk-git
package context: unrecognized import path "context" (import path does not begin with hostname)
deployment@ubuntu:~/tyk-git$
```

Any thoughts ?

**Comment by dijitali** [comment]
I hit the same issue.  The docs here recommend [`go install`](https://golang.org/cmd/go/#hdr-Compile_and_install_packages_and_dependencies) but this doesn't download remote packages.

Instead you need to use [`go get`](https://golang.org/cmd/go/#hdr-Download_and_install_packages_and_dependencies) (which also does the `go install`):
```
go get github.com/TykTechnologies/tyk-git
```

The built binary `tyk-git` is then available as:
```
➜  ~ ./go/bin/tyk-git --help
A tool to use Tyk API Definitions or OAS (Swagger) files stored
		in Git (or potentially other VCS) with the Tyk API Management
		Platform (https://tyk.io)

...
```

**Comment by james-tyk** [comment]
Thanks, will investigate.

**Comment by l3ender** [comment]
Would be nice if the readme (and [docs](https://tyk.io/docs/advanced-configuration/manage-multiple-environments/tyk-sync/)) were updated to reflect the correct install command (`go get -u github.com/TykTechnologies/tyk-sync`).

**Comment by sedkis** [comment]
Will do ASAP. Thanks @l3ender

**Comment by l3ender** [comment]
@sedkis Can you reopen this to track it, or should a different issue be created?

**Comment by l3ender** [comment]
Scratch that--missed your commit (https://github.com/TykTechnologies/tyk-sync/commit/b60db0799c4c325b33de3c3dc0610b515a75c259). Thanks!
