### ISSUE TITLE
syncing

### ISSUE THREAD

**Issue by ybchoo** [TykTechnologies/tyk-sync#104]
Can some one please kindly provide me a step by step instruction on how to perform tyk-sync?
At present, I am working on docker, localhost.
I am trying to tyk-sync to another image with all the data from container 1 to container 2.
Thanks

**Comment by komalsukhani** [comment]
@ybchoo We have improved our docs for Tyk Sync https://tyk.io/docs/product-stack/tyk-sync/overview/
I hope it resolves your issue.

I am closing this issue for now. If you find anything is missing in our docs, please another ticket.
