### ISSUE TITLE
Can't 'publish' policies to tyk cloud SaaS

### ISSUE THREAD

**Issue by nathanschepers** [TykTechnologies/tyk-sync#11]
This looks like a bug to me. Steps to reproduce:

1 - `tyk-sync dump` some api & policy def'ns from a local tyk instance
2 - `tyk-sync publish` these definitions to tyk cloud:

```
./tyk-sync publish -s [KEY] -d https://admin.cloud.tyk.io/ -p ./foo                                  
Fetched 2 definitions
Fetched 1 policies
Using publisher: Dashboard Publisher
Creating API 0: httpbin
--> Status: OK, ID:5d24968f3c6e040001226dc2
Creating API 1: httpbin-authplugin-dev
--> Status: OK, ID:5d249690bdb9a500018dfdab
Creating Policy 0: httpbin-policy
--> Status: FAIL, Error:API Returned error: {"Status":"Error","Message":"Object not owned by this organisation, write is forbidden","Meta":null}
Done
```

I'm not sure why it's able to publish the APIs, but not the policy. I think there is an undocumented 'organization override' option, but I'm not clear on how/when to use it.

**Comment by nathanschepers** [comment]
The same problem happens when trying to `dump` from cloud and `publish` locally:

```
Creating Policy 0: httpbin-policy
--> Status: FAIL, Error:API Returned error: {"Status":"Error","Message":"Object not owned by this organisation, write is forbidden","Meta":null}
Done
```

**Comment by letzya** [comment]
It's not a bug but a feature. We should look into adding this option and expose this as a configuation or not.
