### ISSUE TITLE
Use slug for file names?

### ISSUE THREAD

**Issue by eloo-abi** [TykTechnologies/tyk-sync#14]
Hello,

when working with tyc-sync its pretty hard to see at a glance which api file i've opened.. or directly from the file browser.
So maybe it would be possible to use the slug as a filename for APIS?

This would it make pretty easy to see on which API i'm working on.
What do you think?

Thanks

**Comment by buger** [comment]
Slug is not universal, so maybe somehow use API name in combination with listen path or similar. 
Uniquely identifying API can be a tricky task. Also if slug or listen path will change, it needs detect it and override file, instead of creating new one..

**Comment by eloo** [comment]
Ah okay, yeah listenpath with API name or something like this would also fit our needs.
At something which is a bit human readable

**Comment by letzya** [comment]
@buger maybe api name (change spaces to "_") + the existing id to make sure it's unique?

**Comment by eloo** [comment]
i guess this would also work for us 👍

**Comment by l3ender** [comment]
Including the API/policy name in the file name would be helpful. Not quite sure how it would handle  API/policy name updates, but I do agree it's a little difficult to determine the significance of the current files that have just IDs.

**Comment by l3ender** [comment]
Nice to see an update on this. Is there an ETA for its version and release?
