### ISSUE TITLE
How do you use ty-git with Swagger?

### ISSUE THREAD

**Issue by Krobar** [TykTechnologies/tyk-sync#2]
Sorry if there is documentation somewhere already but I really can't find it. How can I import swagger file with Tyk-git?

**Comment by letzya** [comment]
.tyk.json should look similar to this:

{
    "type": "oas",   
    "files": [{
        "file": "swagger.json",
        "api_id": "OAI1",
	"org_id": "O8",
        "oas": {
             "override_target": "http://testmystuff.com",
             "override_listen_path": "/testing/",
	     "version_name": "" 
        }
    }]
}
