### ISSUE TITLE
Catalogues based on synced Policies are not shown on Catalogues page

### ISSUE THREAD

**Issue by davegarvey** [TykTechnologies/tyk-sync#24]
### Problem 

Catalogues created based on Policies imported via Tyk Sync are invisible in the Dashboard i.e. the `/api/portal/catalogue` Dashboard API endpoint does not return them.

### Description

When I use Tyk Sync to backup and restore Policies across different installations, I find that if I create a catalogue based on one of the synced Policies, the newly created Catalogue item does not appear in the Catalogue listing page in the Dashboard (<DASH_URL>/#/portal/catalogue), but it does appear in the Catalogue listing page in the Portal (<PORTAL_URL>/portal/apis/).

This issue affects only imported Policies, not newly created Policies. If I create a new Policy and then create a Catalogue linked to that, then the Catalogue item is shown as normal. So it is something to do with how Tyk Sync is importing the Policies. The Policies appear to import ok, they are visible in the Dashboard and can be used ok by keys.

This is happening on Dashboard v1.9.4 and Tyk-Sync v1.1.0.

### Replication process

Replication process (assumes you already have dumped sync files and have and the policies do not already exist):
- Run `tyk-sync -d <DASH_URL> -s <DASH_API_CREDS> -p <DATA_LOCATION>`
- Log into Dashboard
- Check Policies page
- Imported Policies will be shown ok
- Go to Catalogues page and create a Catalogue entry based on one of the imported Policies
- Newly created Catalogue will **not** be shown
- Go to Portal and view Catalogues page
- Catalogue will be shown on Portal

### Recording of issue

![catalogues](https://user-images.githubusercontent.com/1711419/80348578-925dff00-88a0-11ea-8f62-5ae2280a8dce.gif)

### Reference object data

For reference, here's an example of a Policy object stored in a Tyk Sync `.json` file:

```json
{
  "_id": "5ea3ddc19445d30001962f47",
  "id": "5ea11155f4f8460001a9389e",
  "org_id": "5e9d9544a1dcd60001d0ed20",
  "rate": 2,
  "per": 5,
  "quota_max": -1,
  "quota_renewal_rate": 3600,
  "access_rights": {
    "accbdd1b89e84ec97f4f16d4e3197d5c": {
      "api_name": "Basic Protected API",
      "api_id": "accbdd1b89e84ec97f4f16d4e3197d5c",
      "versions": [
        "Default"
      ],
      "allowed_urls": []
    }
  },
  "hmac_enabled": false,
  "active": true,
  "name": "Rate Limit Policy",
  "is_inactive": false,
  "date_created": "2020-04-23T03:53:57.116Z",
  "tags": [],
  "key_expires_in": 0,
  "partitions": {
    "quota": false,
    "rate_limit": false,
    "acl": false
  },
  "last_updated": "1587614037"
}
```

**Comment by tbuchaillot** [comment]
PR #23 should solve this.
