### ISSUE TITLE
tyk-sync version

### ISSUE THREAD

**Issue by l3ender** [TykTechnologies/tyk-sync#36]
Is there a way to see what version of tyk-sync I am using? I don't see it under `-h` flag and it doesn't appear there is a `-v` flag.

**Comment by eloo** [comment]
Yep, would be really helpful to have a version command.

**Comment by tbuchaillot** [comment]
@l3ender @eloo this is going to be included in the next Tyk Sync release 👍 #73

**Comment by andyo-tyk** [comment]
Hi! This was implemented in [Tyk Sync v1.2.2](https://github.com/TykTechnologies/tyk-sync#example-check-the-currently-installed-version-of-tyk-sync), sorry for the delay updating this issue.
