### ISSUE TITLE
Work with API ownership to promote APIs through single org environment

### ISSUE THREAD

**Issue by joshblakeley** [TykTechnologies/tyk-sync#47]
Enable passing user group IDs to template onto the apis as they move through an org with API ownership enabled i.e. cloud/ larger on prem installs

Small code change with big productivity gains!

**Comment by joshblakeley** [comment]
This may already work in some ways but definitely needs hardening.

**Comment by letzya** [comment]
related to https://tyktech.atlassian.net/browse/TT-482
