### ISSUE TITLE
TT-12007 How to sync for the first time without Dashboard dump. .tyk.json missing

### ISSUE THREAD

**Issue by brahama** [TykTechnologies/tyk-sync#71]
I am getting an error about missing `.tyk.json` as i did not do a dump from a dashboard. I was not able to found any documentation on how to build this file. Found an old issue with an example but dont undrestand the references.

Aint sync supposed to work on OSS GW? or just with dashboard?

Thanks

**Comment by brahama** [comment]
Hi fellows! Any way to bypass that? pointer to doc?

Thanks!

**Comment by brahama** [comment]
Pretty quiet over here. Is this still being used? or do we have other options?

Thanks

**Comment by tbuchaillot** [comment]
@brahama Hi! can you try creating a `.tyk.json` with the following structure? 

`
{
  "type": "apidef",
  "files": [
    {
      "file": "api-API_ID.json",
      "oas": {}
    }
  ],
  "policies": [
    {
      "file": "policy-POLICY_ID.json"
    }
  ]
}
`
and replace the POLICY_ID and API_ID with your ID's? It should be in the same dir where you have your api-* and policy-* files.

**Comment by brahama** [comment]
Thanks @tbuchaillot ! Will try it over the weekend and come back.

**Comment by brahama** [comment]
@tbuchaillot finally i was able to try it out. looks promising! I did a quick test with just one file and API. No policies and output was ok.

```
Fetched 1 definitions
Fetched 0 policies
Using publisher: Gateway Publisher
Processing APIs...
Deleting: 0
Updating: 0
Creating: 1
```

Tomorrow will try to test a bit deeper but looks like you nailed it. Thanks a bunch! :)

**Comment by brahama** [comment]
Im back @tbuchaillot .. The API def, only tried one seems to be working perfecct, but the policies dont.

```
Fetched 1 definitions
Fetched 1 policies
Using publisher: Gateway Publisher
Processing APIs...
Deleting: 0
Updating: 1
Creating: 0
SYNC Updating: de6f30b5070b4c7d99c7bcdfaafd8bde
Reloading...
Reloading...
```

It kinda looks like it detects the policy but it never process it

tyk.json
```json
{
   "type": "apidef",
   "files": [ { "file": "api-de6f30b5070b4c7d99c7bcdfaafd8bde.json", "oas": {} } ],
   "policies": [{ "file": "policy-61771aa34fb23a000178d4df.json"}]
}
```

I moved tyk gateway to version 4.1 RC that has support for policies endpoint.. Just in case that might be breaking it..

Thanks in advanced! :)

**Comment by ybchoo** [comment]
![2022-12-16 Tyk Sync](https://user-images.githubusercontent.com/3133110/208035320-a8212201-0676-471f-a778-156227766b42.JPG)
Can someone please kindly let me know where when I uses Tyk Sync I keep getting the attached problems.?

**Comment by ajrice6713** [comment]
I am facing the same issue as @ybchoo - is `tyk-sync` only for cloud/self-managed customers? It seems like the dashboard/portal is not available to open-source users.

**Comment by oluwaseyeayinla** [comment]
@ajrice6713 Yes, the dashboard is closed-source and requires a [license](https://tyk.io/docs/apim/#licensing). Hence, it is not available to open-source users. If you have further issues with sync, then please visit our [community forums page](https://community.tyk.io/c/support/6). We are always happy to help.

**Comment by oluwaseyeayinla** [comment]
@ybchoo The issue you are facing is a connection issue. I don't think it's Tyk-related. You need to ensure the dashboard machine is not blocking any connections and that your client machine can also reach the dashboard. A simple curl from the client machine would give you a hint.

Also, it would be nice if you could open a new thread or issue to continue the conversation. This issue is related to syncing and not dumping from the dashboard

**Comment by oluwaseyeayinla** [comment]
@brahama Did you manage to resolve the issue? Could it be related to `policies.allow_explicit_policy_id` or maybe needing to publish before syncing?

**Comment by oluwaseyeayinla** [comment]
Think the policies sync might only work for the dashboard. 
@tbuchaillot Can you confirm if the policy sync can also work for gateways?

**Comment by komalsukhani** [comment]
@brahama We have improved Tyk Documentation for [Sync](https://tyk.io/docs/product-stack/tyk-sync/overview/).
Please raise another issue if still it doesn't solve the problem. Closing this issue for now.
