### ISSUE TITLE
TT-8924 Publish / update commands should return non-zero exit code on failure

### ISSUE THREAD

**Issue by dmayo3** [TykTechnologies/tyk-sync#76]
In order to use this in a CI/CD or scripting context, it's currently necessary to parse the tyk-sync stdout in order to detect failure, instead of being able to rely on non-zero exit codes.

As you can see from this example the logic just prints errors and then carries on:

https://github.com/TykTechnologies/tyk-sync/blob/a257afd708d119405ff5768a6447552268adaf2d/cmd/shared.go#L258-L260

There are other lines like this further down in the code, and possibly in other functions as well.

**Comment by tbuchaillot** [comment]
Hi @dmayo3, thanks for raising this! We are aware of this issue and plan to fix it in one of our subsequent minor releases. 

I'll let you know here when that happens.

**Comment by komalsukhani** [comment]
This issue is already resolved.
